version: "3.10"

services:
  nosqldata:
    image: mongo
    
  recipe-api:
    image: ${REGISTRY:-ghcr.io/librecuisine}/recipe.api:${TAG:-develop}
    build:
      context: .
      dockerfile: Services/Recipe/Recipe.API/Dockerfile
    depends_on:
      - nosqldata
  
  gateway-api:
    image: envoyproxy/envoy:v1.24-latest
    depends_on:
      - recipe-api