version: "3.10"

services:
  nosqldata:
    ports:
      - "27017:27017"
    volumes:
      - librecuisine-nosqldata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${NO_SQL_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${NO_SQL_PASS:-password}
      
  identitydata:
    ports:
      - "54321:5432"
    volumes:
      - librecuisine-identitydata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${ID_PASS:-password}
      POSTGRES_USER: ${ID_USER:-root}
      POSTGRES_DB: "identity"
  
  identity-api:
    ports:
      - "5102:80"
    volumes:
      - ~/.librecuisine:/app/keys:ro
    environment:
      JWT__PRIVATEKEYPATH: "/app/keys/privatekey.pem"
      JWT__PUBLICKEYPATH: "/app/keys/publickey.pem"
      JWT__ISSUER: "http://localhost:5200"
      CONNECTIONSTRINGS__POSTGRESCONNECTION: "Server=identitydata;Port=5432;Database=identity;User Id=${ID_USER:-root};Password=${ID_PASS:-password};"
  recipe-api:
    ports:
      - "5101:80"
    environment:
      DATABASE__DATABASENAME: "RecipeDB"
      DATABASE__COLLECTIONNAME: "Recipes"
      DATABASE__CONNECTIONSTRING: "mongodb://${NO_SQL_USER:-root}:${NO_SQL_PASS:-password}@nosqldata:27017"

  gateway-api:
    volumes:
      - ./ApiGateway/Envoy/config:/etc/envoy
    ports:
      - "5200:80"
      - "15200:8001"
      
  mongo-express:
    ports:
      - "8081:8081"
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${NO_SQL_USER:-root}:${NO_SQL_PASSWORD:-password}@nosqldata:27017"
    depends_on:
      - nosqldata

volumes:
  librecuisine-nosqldata:
    external: false
  librecuisine-identitydata:
    external: false
networks:
  default:
    name: librecuisine-network
    external: false
