version: "3.10"

services:
  nosqldata:
    image: mongo

  identitydata:
    image: postgres

  identity-api:
    image: ${REGISTRY:-ghcr.io/librecuisine}/identity.api:${TAG:-develop}
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - identitydata

  recipe-api:
    image: ${REGISTRY:-ghcr.io/librecuisine}/recipe.api:${TAG:-develop}
    build:
      context: .
      dockerfile: Services/Recipe/Recipe.API/Dockerfile
    depends_on:
      - nosqldata

  gateway-api:
    image: envoyproxy/envoy:v1.24-latest
    depends_on:
      - recipe-api

  rabbitmq:
    image: rabbitmq:3-management
