name: recipe-api

on:
  push:
    branches:
      - develop
    paths:
      - src/Services/Recipe/**
      - .github/workflows/recipe-api.yml
  pull_request:
    branches:
      - develop
    paths:
      - src/Services/Recipe/**
      - .github/workflows/recipe-api.yml
      
permissions:
  contents: read
  packages: write
  
jobs:
  BuildContainersPR:
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/build
        with: 
          service: recipe-api
          registry_endpoint: ghcr.io/${{ github.repository_owner }}
          
  BuildContainersAndPush:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/build-push
        with: 
          service: recipe-api
          registry_host: ghcr.io
          registry_endpoint: ghcr.io/${{ github.repository_owner }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
